// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHjMPNmBGaDdkc00DwHZhiaagGNaKISP8',
    appId: '1:609797109604:web:a31f4ccb96e9c978f12c71',
    messagingSenderId: '609797109604',
    projectId: 'my-flutter-app-hezra-202-12dc9',
    authDomain: 'my-flutter-app-hezra-202-12dc9.firebaseapp.com',
    storageBucket: 'my-flutter-app-hezra-202-12dc9.firebasestorage.app',
    measurementId: 'G-C14Q6H024F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKaFmilc3TrmwCsM6vAoSNTd498AG6NhA',
    appId: '1:609797109604:android:472c1897ef2d9b9df12c71',
    messagingSenderId: '609797109604',
    projectId: 'my-flutter-app-hezra-202-12dc9',
    storageBucket: 'my-flutter-app-hezra-202-12dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkVhYQhVje93B3P4LYzy7b7KYOkWQ2CQ',
    appId: '1:609797109604:ios:c578223f85045f68f12c71',
    messagingSenderId: '609797109604',
    projectId: 'my-flutter-app-hezra-202-12dc9',
    storageBucket: 'my-flutter-app-hezra-202-12dc9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFkVhYQhVje93B3P4LYzy7b7KYOkWQ2CQ',
    appId: '1:609797109604:ios:c578223f85045f68f12c71',
    messagingSenderId: '609797109604',
    projectId: 'my-flutter-app-hezra-202-12dc9',
    storageBucket: 'my-flutter-app-hezra-202-12dc9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHjMPNmBGaDdkc00DwHZhiaagGNaKISP8',
    appId: '1:609797109604:web:f750672292d7d970f12c71',
    messagingSenderId: '609797109604',
    projectId: 'my-flutter-app-hezra-202-12dc9',
    authDomain: 'my-flutter-app-hezra-202-12dc9.firebaseapp.com',
    storageBucket: 'my-flutter-app-hezra-202-12dc9.firebasestorage.app',
    measurementId: 'G-JGGBPXX0FC',
  );
}
